# Generated by Django 3.1.5 on 2021-01-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikisearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractor',
            name='description',
            field=models.TextField(blank=True, help_text='Enter the text', null=True),
        ),
    ]
